---
- name: check kibana
  stat: path={{ kibana.destination }}/kibana-{{ kibana.version }}
  register: kibanapath

- name: install required packages
  apt: pkg={{ item }} state=latest
  with_items:
    - elasticsearch

- name: download kibana archive
  get_url: url={{ kibana.url }} dest=/tmp/kibana-{{ kibana.version }}.zip
  when: kibanapath.stat.isdir is not defined

- name: extract kibana archive
  unarchive: src=/tmp/kibana-{{ kibana.version }}.zip dest={{ kibana.destination }} copy=no
  when: kibanapath.stat.isdir is not defined
  
- name: clean temporary files
  command: "{{ item }}"
  with_items:
      - rm -f /tmp/kibana-{{ kibana.version }}.zip
  when: kibanapath.stat.isdir is not defined
  ignore_errors: yes